fin = open("ssl_pinning_bypass.py", "rt")
data = fin.read()
data = data.replace('adb','./../adb')
data = data.replace('FLAG2 = \"CHANGED\"','FLAG2 = \"UNCHANGED\"')
data = data.replace("If you want to use this with genymotion, run the command, \" python3 with_geny.py\"","It is adviced to clone the SSL-bypass tool in the \"/genymotion/tools\" directory. If you are not using Genymotion, please use the following command,\"python3 no_geny.py\" and try again")
fin.close()
fin = open("ssl_pinning_bypass.py", "wt")
fin.write(data)
fin.close()